[package]
name = "ono-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
color-eyre = "0.6.5"
crossterm = "0.29.0"
dirs = "6.0.0"
env_logger = "0.11.8"
log = "0.4.29"
ratatui = "0.30.0"
